export default {
  maxPuzzleSize: 10,
  defaultPuzzle: 3,
  outputFormat: 'svg',
  outputSize: 128,
  view: '',
  stage: '',
  rotation: ['y45', 'x-34'],
  alg: '',
  case: '',
  faceletDefinition: '',
  faceletColours: '',
  colourScheme: {
    U: '#FFFFFF',
    R: '#EE0000',
    F: '#00D800',
    L: '#FFA100',
    D: '#FEFE00',
    B: '#0000F2',
    N: '#404040',
    T: 't',
  },
  backgroundColour: 'white',
  cubeColour: 'black',
  cubeOpacity: 100,
  faceletOpacity: 100,
  distance: 5,
  outputFormatOptions: ['jpeg', 'jpg', 'png', 'tiff', 'webp'],
  OUTLINE_WIDTH: 0.94,
  sw: 0,
  ox: -0.9,
  oy: -0.9,
  vw: 1.8,
  vh: 1.8,
  rv: [
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, -1],
    [0, 1, 0],
    [-1, 0, 0],
    [0, 0, 1],
  ],
  defaultSize: 128,
};
